INSERT INTO [localidad] (nombre)
VALUES
  ('Dutse'),
  ('Flushing'),
  ('Gyeongsan'),
  ('Villahermosa'),
  ('Kawerau'),
  ('Guadalupe'),
  ('Altach'),
  ('Sevsk'),
  ('Kirov'),
  ('Khyber Agency'),
  ('Pontevedra'),
  ('Topeka'),
  ('Hải Phòng'),
  ('Mo i Rana'),
  ('Avignon'),
  ('Cork'),
  ('Kollam'),
  ('Cagayan de Oro'),
  ('Hồ Chí Minh City'),
  ('Sungai Penuh');
INSERT INTO [localidad] (nombre)
VALUES
  ('Sasolburg'),
  ('Middelburg'),
  ('Moffat'),
  ('Koszalin'),
  ('Abbeville'),
  ('Veere'),
  ('Ceuta'),
  ('Canora'),
  ('Mérida'),
  ('Canberra'),
  ('Boo'),
  ('Uribia'),
  ('Cork'),
  ('Florenville'),
  ('Belfast'),
  ('Tomaszów Mazowiecki'),
  ('Przemyśl'),
  ('Macau'),
  ('Isabela City'),
  ('Nuevo Laredo');
INSERT INTO [localidad] (nombre)
VALUES
  ('Parys'),
  ('Drohobych'),
  ('Oldenzaal'),
  ('Goiânia'),
  ('Buckley'),
  ('Cumbernauld'),
  ('Ovalle'),
  ('Kungälv'),
  ('Hartford'),
  ('Cartago');
