INSERT INTO [provincia] (nombre)
VALUES
  ('Konya'),
  ('Montgomeryshire'),
  ('Querétaro'),
  ('East Kalimantan'),
  ('Sląskie'),
  ('Montana'),
  ('Cheshire'),
  ('Guerrero'),
  ('Ivano-Frankivsk oblast'),
  ('Phú Yên'),
  ('Vestland'),
  ('Huáběi'),
  ('Western Cape'),
  ('San Luis Potosí'),
  ('Puno'),
  ('Madrid'),
  ('Guanajuato'),
  ('Gauteng'),
  ('Huádōng'),
  ('Małopolskie');
INSERT INTO [provincia] (nombre)
VALUES
  ('KwaZulu-Natal'),
  ('Vienna'),
  ('Alajuela'),
  ('Ceará'),
  ('Balochistan'),
  ('Wiltshire'),
  ('Maule'),
  ('North Island'),
  ('Overijssel'),
  ('Leinster'),
  ('Kayseri'),
  ('North-East Region'),
  ('Central Region'),
  ('Bretagne'),
  ('Northern Cape'),
  ('North Island'),
  ('Heredia'),
  ('Zhytomyr oblast'),
  ('İzmir'),
  ('Free State');
INSERT INTO [provincia] (nombre)
VALUES
  ('Cagayan Valley'),
  ('Ceará'),
  ('Cajamarca'),
  ('Long An'),
  ('Samara Oblast'),
  ('Extremadura'),
  ('Podkarpackie'),
  ('Niger'),
  ('Córdoba'),
  ('Los Ríos');
