INSERT INTO [documentacion] (nombre,descripcion,direccion_url,id_cliente)
VALUES
  ('facilisis vitae, orci.','a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed','http://ebay.com/fr',10),
  ('dignissim magna a','lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium','http://naver.com/sub/cars',33),
  ('nisi. Mauris nulla.','lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna,','https://wikipedia.org/en-us',33),
  ('Sed malesuada augue','mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor.','https://guardian.co.uk/user/110',43),
  ('a mi fringilla','nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam.','http://netflix.com/user/110',20),
  ('erat volutpat. Nulla','hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque','https://pinterest.com/fr',29),
  ('libero. Donec consectetuer','Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui.','http://ebay.com/settings',17),
  ('augue porttitor interdum.','Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna','https://netflix.com/one',17),
  ('Aliquam erat volutpat.','diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula.','http://twitter.com/en-ca',19),
  ('elementum sem, vitae','ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec','https://pinterest.com/user/110',45),
  ('amet, dapibus id,','commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec','http://pinterest.com/user/110',50),
  ('hendrerit consectetuer, cursus','libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum','https://wikipedia.org/en-us',9),
  ('imperdiet, erat nonummy','lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus.','http://wikipedia.org/user/110',33),
  ('venenatis a, magna.','enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in,','http://yahoo.com/site',8),
  ('montes, nascetur ridiculus','natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl.','https://reddit.com/one',24),
  ('nec mauris blandit','ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet','http://reddit.com/user/110',41),
  ('Aliquam ultrices iaculis','ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae','https://baidu.com/settings',35),
  ('orci. Phasellus dapibus','dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in','http://guardian.co.uk/settings',7),
  ('tempus risus. Donec','sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac','https://zoom.us/en-us',39),
  ('pede nec ante','cubilia Curae Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed','http://reddit.com/sub/cars',39);
INSERT INTO [documentacion] (nombre,descripcion,direccion_url,id_cliente)
VALUES
  ('sed, est. Nunc','magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a','http://reddit.com/en-ca',28),
  ('lobortis risus. In','Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel,','http://cnn.com/settings',9),
  ('Maecenas libero est,','auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu,','https://netflix.com/en-us',28),
  ('iaculis nec, eleifend','Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse','http://zoom.us/group/9',10),
  ('hendrerit consectetuer, cursus','posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh','https://reddit.com/en-ca',7),
  ('lacus, varius et,','netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam','http://whatsapp.com/fr',47),
  ('Aliquam tincidunt, nunc','amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy','http://yahoo.com/one',46),
  ('lobortis, nisi nibh','mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in,','https://youtube.com/group/9',30),
  ('Nulla semper tellus','Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas,','http://naver.com/sub/cars',33),
  ('aliquam eros turpis','malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed','https://naver.com/en-ca',33),
  ('gravida. Aliquam tincidunt,','eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem.','https://yahoo.com/en-ca',34),
  ('vel, faucibus id,','natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo','https://netflix.com/settings',20),
  ('urna convallis erat,','Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc','https://google.com/sub/cars',17),
  ('non, lobortis quis,','Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante','http://facebook.com/sub/cars',28),
  ('sem eget massa.','sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales','http://facebook.com/sub',12),
  ('Cum sociis natoque','purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis','http://wikipedia.org/group/9',22),
  ('Aliquam gravida mauris','faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing.','https://baidu.com/settings',36),
  ('pellentesque. Sed dictum.','faucibus orci luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui.','https://guardian.co.uk/sub',25),
  ('montes, nascetur ridiculus','amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam.','http://google.com/en-ca',10),
  ('nibh. Phasellus nulla.','Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat','http://nytimes.com/fr',10);
INSERT INTO [documentacion] (nombre,descripcion,direccion_url,id_cliente)
VALUES
  ('eget, venenatis a,','a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit','https://baidu.com/group/9',25),
  ('Phasellus dolor elit,','est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo','http://google.com/one',47),
  ('in faucibus orci','mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat','https://google.com/group/9',45),
  ('primis in faucibus','Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis','http://youtube.com/group/9',24),
  ('interdum. Nunc sollicitudin','Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec','http://naver.com/en-ca',41),
  ('neque. Nullam ut','nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu.','http://twitter.com/settings',36),
  ('lectus. Cum sociis','semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi','https://naver.com/user/110',37),
  ('in, dolor. Fusce','gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a,','http://instagram.com/sub',49),
  ('Suspendisse non leo.','dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero.','https://zoom.us/en-us',28),
  ('quam. Pellentesque habitant','risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum.','https://netflix.com/sub',31);
