INSERT INTO [propiedad_foto] (codigo_propiedad,foto)
VALUES
  (12,'https://domus.ar/user/110'),
  (12,'https://reddit.com/group/9'),
  (14,'ftp://reddit.com/group/9'),
  (11,'ftp://pinterest.com/en-ca'),
  (9,'ftp://wikipedia.org/group/9'),
  (23,'http://instagram.com/image/property'),
  (14,'ftp://nytimes.com/fr'),
  (18,'ftp://domus.br/site'),
  (3,'https://bbc.co.uk/group/9'),
  (6,'http://netflix.com/en-ca'),
  (14,'https://twitter.com/sub'),
  (9,'https://domus.com/group/9'),
  (13,'http://google.com/sub/cars'),
  (8,'ftp://ebay.com/sub'),
  (24,'https://cnn.com/sub'),
  (27,'ftp://walmart.com/user/110'),
  (20,'ftp://baidu.com/sub/cars'),
  (30,'https://netflix.com/image'),
  (8,'ftp://domus.br/group/9'),
  (2,'https://wikipedia.org/settings');
INSERT INTO [propiedad_foto] (codigo_propiedad,foto)
VALUES
  (9,'https://google.com/user/110'),
  (13,'https://wikipedia.org/en-us'),
  (8,'https://youtube.com/image'),
  (23,'ftp://facebook.com/group/9'),
  (9,'http://domus.br/group/9');
