INSERT INTO [cita] (estado,descripcion,fecha_hs,motivo,legajo_secretaria,legajo_agente,id_cliente,codigo_inmueble)
VALUES
  ('en proceso','sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis','20230403','Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare',14,22,11,11),
  ('cancelado','nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget,','20220413','elementum, dui quis accumsan convallis, ante lectus convallis est, vitae',16,22,7,6),
  ('finalizado','lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede,','20230818','mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent',16,24,16,9),
  ('cancelado','orci luctus et ultrices posuere cubilia Curae Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas','20220430','malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis',18,21,18,11),
  ('finalizado','porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula','20230321','Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis',16,30,22,6),
  ('en proceso','sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus, accumsan','20230722','tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque',13,23,9,7),
  ('en proceso','nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum','20211220','euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas',16,28,10,14),
  ('cancelado','suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non','20230308','amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.',17,28,26,7),
  ('cancelado','nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et,','20230628','Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit.',15,27,23,13),
  ('en proceso','ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices,','20230211','Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae',16,25,13,13),
  ('en proceso','Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus','20230328','eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus',20,22,12,10),
  ('cancelado','pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam','20231005','mus. Proin vel arcu eu odio tristique pharetra. Quisque ac',20,25,26,5),
  ('finalizado','dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis,','20230616','dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent',19,29,4,14),
  ('en proceso','turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis.','20211223','In at pede. Cras vulputate velit eu sem. Pellentesque ut',16,28,19,8),
  ('cancelado','dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum','20221217','non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis',14,30,25,15);
